---
title: "Course support"
---

{{< video https://www.youtube.com/embed/ZS8QHRtzcPg >}}

Most of you will need help at some point and we want to make sure you can identify when that is without getting too frustrated and feel comfortable seeking help. Please follow the **15 minute rule** in this class.

{{< tweet math_rachel 764931533383749632 >}}

If you are stuck on a problem, you should attempt to fix it on your own for 15 minutes. After 15 minutes, you **must** ask for help.

## Lectures and labs

If you have a question during lecture or lab, feel free to ask it! There are likely other students with the same question, so by asking you will create a learning opportunity for everyone.

## Office hours

The teaching team is here to help you be successful in the course. You are encouraged to attend office hours during the times posted on the home page to ask questions about the course content and assignments. A lot of questions are most effectively answered in-person, so office hours are a valuable resource. I encourage each and every one of you to take advantage of this resource!

Make a pledge to stop by office hours at least once during the first three weeks of class. If you truly have no questions to ask, just stop by and say hi and introduce yourself. You can find a list of everyone's office hours [here](/course-team.qmd).

## GitHub Discussions

Have a question that can't wait for office hours? Prefer to write out your question in detail rather than asking in person? The [course discussion forum](https://github.coecis.cornell.edu/orgs/info2950-s23/discussions). There is a chance another student has already asked a similar question, so please check the other posts on GitHub Discussions before adding a new question. If you know the answer to a question posted on the discussion board, I encourage you to respond!

## Email

Please refrain from emailing any course content questions (those should go to office hours or GitHub Discussions), and only use email for questions about personal matters that may not be appropriate for the public course forum (e.g., illness, accommodations, etc.). For such matters, you may email Dr. Benjamin Soltoff at [info2950-prof\@cornell.edu](mailto:info2950-prof@cornell.edu).

If there is a question that's not appropriate for a public discussion forum, you are welcome to email me directly. Barring extenuating circumstances, I will respond to INFO 2950 emails within 48 hours Monday - Friday. Response time may be slower for emails sent Friday evening - Sunday.

## Academic support

Sometimes you may need help with the class that is beyond what can be provided by the course staff. Cornell offers multiple centers to support student learning. The [Learning Strategies Center (LSC)](https://lsc.cornell.edu/) offers programs and resources to develop effective approaches to the learning process and become a successful and independent student. They host workshops, provide online resources, and offer private consultations for one-on-one support to develop effective learning strategies. Contact [learningstrategiescenter\@cornell.edu](mailto:learningstrategiescenter@cornell.edu) to setup an appointment.

## Mental health and wellness

If your mental health concerns and/or stressful events negatively affect your daily emotional state, academic performance, or ability to participate in your daily activities, many resources are available to help you through difficult times. [Counseling & Psychological Services](https://health.cornell.edu/services/mental-health-care) at Cornell Health provides professional and confidential mental health care to help you “live well to learn well” here at Cornell. Their services include self-care resources and programming, workshops, informal consultations, individual and group counseling, and referrals to off-campus mental health providers. To schedule an access appointment, log in to[ myCornellHealth](https://mycornellhealth.health.cornell.edu/) using your Cornell NetID and password, and select Appointments. You may also call 607-255-5155 during business hours to schedule.

## Course costs

-   **Textbooks:** The textbooks for this course are freely available on the web.
-   **Laptops:** Each student is expected to have a laptop they can bring to each lecture and lab.

If you are having difficulty with costs associated with this course, here are some resources:

-   [Contact the financial aid office](https://finaid.cornell.edu/ "https://finaid.cornell.edu/") (whether or not you are on aid).
    They have loans and resources for connecting students with programs on campus that might be able to help alleviate these costs.
