---
title: "INFO 3312/5312: Data Communication"
execute:
  freeze: false
---

This page contains an outline of the topics, content, and assignments for the semester.
Note that this schedule will be updated as the semester progresses and the timeline of topics and assignments might be updated throughout the semester.

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(googlesheets4)
library(gt)
library(tidyverse)

d <- read_sheet("https://docs.google.com/spreadsheets/d/1cBS3rzkaDqRH6AIdENrcH89UZ_C_djqeq8yF0E8A52g/edit#gid=0")
```

::: column-screen-right
```{r, echo = FALSE}
d |>
  # remove module column - just for planning purposes
  select(-module) |>
  mutate(
    date = as.Date(date),
    week = ifelse(is.na(week), "", week)
  ) |>
  gt() |>
  text_transform(cells_body(columns = c(prepare)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("book", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('book')}</a>")
      )
    }
  ) |>
  text_transform(cells_body(columns = c(slides)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("laptop", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('laptop')}</a>")
      )
    }
  ) |>
  text_transform(cells_body(columns = c(hw)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("keyboard", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('keyboard')}</a>")
      )
    }
  ) |>
  text_transform(cells_body(columns = c(project)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("users", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('users')}</a>")
      )
    }
  ) |>
  fmt_date(date, date_style = "MMMd") |>
  sub_missing(columns = c(date, what, topic, notes), missing_text = "") |>
  cols_align(
    align = "center", 
    columns = c(week, dow, prepare, slides, hw, project)
    ) |>
  cols_align(
    align = "left", 
    columns = c(date, what, topic, notes)
    ) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#D3D3D3",
      style = "solid"
    ),
    locations = cells_body(
      columns = c(date, topic, prepare, project)
    )
  )
```
:::
